__variables__:
    mpvfifo: ~/.local/share/mpv/fifo
mpv:
    rewind: echo seek -5 > {mpvfifo}
    play/pause: echo cycle pause > {mpvfifo}
    fast forward: echo seek 5 > {mpvfifo}
cliclick:
    left: cliclick kp:arrow-left
    spacebar: cliclick kp:space
    right: cliclick kp:arrow-right
    enter: cliclick kp:return
    esc: cliclick kp:esc
    click: cliclick c:.
    doubleclick: cliclick dc:.
announcer:
    greet: say hello
    part: say farewell
